[Interface]
PrivateKey = <LLAVE_PRIVADA>
Address = 10.0.0.X/24
DNS = 1.1.1.1

[Peer]
PublicKey = <LLAVE_PUBLICA_HUB>
Endpoint = <IP_VM_HUB>:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
